/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_winplus_serial_utils_SerialPort */

#ifndef _Included_org_winplus_serial_utils_SerialPort
#define _Included_org_winplus_serial_utils_SerialPort
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     Java_kuyou_common_serialport_base_SerialPort
 * Method:    setDataBits
 * Signature: ()V
 * 设置串口数据位数
 * @param dataBits 类型 int数据位 取值 位7或8
 */
JNIEXPORT void JNICALL Java_kuyou_common_serialport_base_SerialPort_setDataBits
  (JNIEnv *, jclass, jint);

/*
 * Class:     Java_kuyou_common_serialport_base_SerialPort
 * Method:    setStopBits
 * Signature: ()V
 * 设置串口停止位
 * @param stopBits 类型 int 停止位 取值1 或者 2
 */
JNIEXPORT void JNICALL Java_kuyou_common_serialport_base_SerialPort_setStopBits
  (JNIEnv *, jclass, jint);

/*
 * Class:     Java_kuyou_common_serialport_base_SerialPort
 * Method:    setCheckBits
 * Signature: ()V
 * 设置串口校验位
 * @param checkBits 类型 char 校验类型 取值N ,E, O,,S
 */
JNIEXPORT void JNICALL Java_kuyou_common_serialport_base_SerialPort_setCheckBits
  (JNIEnv *, jclass, jchar);

/*
 * Class:     Java_kuyou_common_serialport_base_SerialPort
 * Method:    setVTime
 * Signature: ()V
 * 设置等待时间
 * @param vTime 类型 int ,单位百毫秒
 */
JNIEXPORT void JNICALL Java_kuyou_common_serialport_base_SerialPort_setVTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     Java_kuyou_common_serialport_base_SerialPort
 * Method:    setVMini
 * Signature: ()V
 * 设置最小接收字符
 * @param vMini 类型 int
 */
JNIEXPORT void JNICALL Java_kuyou_common_serialport_base_SerialPort_setVMini
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_winplus_serial_utils_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_kuyou_common_serialport_base_SerialPort_open
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_winplus_serial_utils_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kuyou_common_serialport_base_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
